const Menu =[
    {
       id : 1,
       image: "images/pizza.jpg",
       name: "Pizza",
       category: "breakfast",
       price: 245,
       description: " lorem25 hshshbs  a a aj jnd kdj jdnwk kddjnd nnajnja  njnsjdb wu snjsjs ahbd sadwad  abdkada idjan daudbasbdsa d maauasdd ahsshiww  sjs sebdddb a   abakdhud ",
    },
    {
        id : 2,
        image: "images/samosa.webp",
        name: "Samosa",
        category: "breakfast",
        price: 225,
        description: "lore m25 hshs hbs snjsjs ahb dsadw ad  abdkad  aidjan daudbasbdsa d maauasdd ahsshiww  sjs sebdddb a   abakdhud ",
     },
     {
        id : 3,
        image: "images/thali.jpg",
        name: "Thali",
        category: "lunch",
        price: 235,
        description: "lor em25 hshs hbs snjs js ah bd  sad wad  abdkadaidjan daudbasbdsa d maauasdd ahsshiww  sjs sebdddb a   abakdhud ",
     },
     {
        id : 4,
        image: "images/idli breafast.jpg",
        name: "Idli",
        category: "lunch",
        price: 215,
        description: "lorem25 hshsh bs snj sjs ahb dsa dwa d  abdka daidjan da udb   as bdsa d maau  asdd ahsshiww  sjs seb dddb a   abakdhud ",
     },
     {
        id : 5,
        image: "images/jhol-momo.png",
        name: "Momo",
        category: "evening",
        price: 258,
        description: "lorem25 hshshbs s njsjs ahbd s adwad  abdkadaidjan daudbasbdsa d maauasdd ahsshiww  sjs sebdddb a   abakdhud ",
     },
     {
        id : 6,
        image: "images/paratha.jpg",
        name: "Paratha",
        category: "evening",
        price: 257,
        description: "lorem25 hshshbs snjsjs ahbdsadwad  abdkadaidjan daudbasbdsa d maauasdd ahsshiww  sjs sebdddb a   abakdhud ",
     },
     {
        id : 7,
        image: "images/new breakfast.webp",
        name: "New break",
        category: "dinner",
        price: 295,
        description: "lorem25 hshshbs snjsjs ahbdsadwad  abdkadaidjan daudbasbdsa d maauasdd ahsshiww  sjs sebdddb a   abakdhud ",
     },
     {
        id : 8,
        image: "images/sweet.webp",
        name: "Sweets",
        category: "dinner",
        price: 205,
        description: "lorem25 hshshbs snjsjs ahbdsadwad  abdkadaidjan daudbasbdsa d maauasdd ahsshiww  sjs sebdddb a   abakdhud ",
     },
     {
        id : 9,
        image: "images/pizza.jpg",
        name: "Maggi",
        category: "lunch",
        price: 125,
        description: "lorem25 hshshbs snjsjs ahbdsadwad  abdkadaidjan daudbasbdsa d maauasdd ahsshiww  sjs sebdddb a   abakdhud ",
     },
     {
      id : 10,
      image: "images/sweet.webp",
      name: "Mohit",
      category: "Mohit",
      price: 2500,
      description: "lorem25 hshshbs snjsjs ahbdsadwad  abdkadaidjan daudbasbdsa d maauasdd ahsshiww  sjs sebdddb a   abakdhud ",
   }
];
export default Menu;